### ISSUE TITLE
Formato de código

### ISSUE THREAD

**Issue by EstebanAGG** [SebastianSegui/ColoresJavaFX#11]
El código está bastante bien. 
La única cuestión que he visto es que no respetáis la longitud de 80 columnas. Veréis que en Netbeans sale una línea cuando estáis programando a la derecha. Pues vuestro código no debe pasar de esa línea.

Os agradecería que revisárais vuestro código e hiciéseis que cumpliera esto. Cualquier programador que se quiera llamar como tal, lo hace de esta forma.

**Comment by SebastianSegui** [comment]
Resuelto el problema con la longitud
